<h1>NumPy<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#NumPy" data-toc-modified-id="NumPy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>NumPy</a></span><ul class="toc-item"><li><span><a href="#Der-Datentyp-numpy.ndarray-(the-game-changer!)" data-toc-modified-id="Der-Datentyp-numpy.ndarray-(the-game-changer!)-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Der Datentyp <code>numpy.ndarray</code> (the game changer!)</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Grundlegendes-Konzept:-Vektorisierung" data-toc-modified-id="Grundlegendes-Konzept:-Vektorisierung-2.1.0.1"><span class="toc-item-num">2.1.0.1&nbsp;&nbsp;</span>Grundlegendes Konzept: Vektorisierung</a></span></li></ul></li></ul></li><li><span><a href="#Vektorisierte-Funktion" data-toc-modified-id="Vektorisierte-Funktion-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Vektorisierte Funktion</a></span></li><li><span><a href="#Das-Erzeugen-von-numpy.ndarrays" data-toc-modified-id="Das-Erzeugen-von-numpy.ndarrays-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Das Erzeugen von numpy.ndarrays</a></span><ul class="toc-item"><li><span><a href="#Ausgewählte-Attribute" data-toc-modified-id="Ausgewählte-Attribute-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>Ausgewählte Attribute</a></span></li><li><span><a href="#Funktionen-zum-Erzeugen-von-numpy.ndarray" data-toc-modified-id="Funktionen-zum-Erzeugen-von-numpy.ndarray-2.3.2"><span class="toc-item-num">2.3.2&nbsp;&nbsp;</span>Funktionen zum Erzeugen von <code>numpy.ndarray</code></a></span></li><li><span><a href="#Kombinationen" data-toc-modified-id="Kombinationen-2.3.3"><span class="toc-item-num">2.3.3&nbsp;&nbsp;</span>Kombinationen</a></span></li><li><span><a href="#Slicing-(Zugriff-auf-Elemente-im-numpy.ndarray)" data-toc-modified-id="Slicing-(Zugriff-auf-Elemente-im-numpy.ndarray)-2.3.4"><span class="toc-item-num">2.3.4&nbsp;&nbsp;</span>Slicing (Zugriff auf Elemente im <code>numpy.ndarray</code>)</a></span></li></ul></li><li><span><a href="#Zfs" data-toc-modified-id="Zfs-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Zfs</a></span></li><li><span><a href="#Operationen" data-toc-modified-id="Operationen-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Operationen</a></span><ul class="toc-item"><li><span><a href="#Elementweise-Operationen" data-toc-modified-id="Elementweise-Operationen-2.5.1"><span class="toc-item-num">2.5.1&nbsp;&nbsp;</span>Elementweise Operationen</a></span></li><li><span><a href="#Matrix-Vektor-Produkt-np.dot,-`@'" data-toc-modified-id="Matrix-Vektor-Produkt-np.dot,-`@'-2.5.2"><span class="toc-item-num">2.5.2&nbsp;&nbsp;</span>Matrix-Vektor Produkt <code>np.dot</code>, `@'</a></span></li><li><span><a href="#Matrix-Matrix-Produkt-np.dot,-@,-np.matmul" data-toc-modified-id="Matrix-Matrix-Produkt-np.dot,-@,-np.matmul-2.5.3"><span class="toc-item-num">2.5.3&nbsp;&nbsp;</span>Matrix-Matrix Produkt <code>np.dot</code>, <code>@</code>, <code>np.matmul</code></a></span></li><li><span><a href="#Transponieren-.T,-.transpose()" data-toc-modified-id="Transponieren-.T,-.transpose()-2.5.4"><span class="toc-item-num">2.5.4&nbsp;&nbsp;</span>Transponieren <code>.T</code>, <code>.transpose()</code></a></span></li><li><span><a href="#Vergleichen" data-toc-modified-id="Vergleichen-2.5.5"><span class="toc-item-num">2.5.5&nbsp;&nbsp;</span>Vergleichen</a></span></li><li><span><a href="#Beachte:-numpy-arrays-sind-veränderlich!" data-toc-modified-id="Beachte:-numpy-arrays-sind-veränderlich!-2.5.6"><span class="toc-item-num">2.5.6&nbsp;&nbsp;</span>Beachte: numpy arrays sind veränderlich!</a></span></li><li><span><a href="#Ausgewählte-Methoden" data-toc-modified-id="Ausgewählte-Methoden-2.5.7"><span class="toc-item-num">2.5.7&nbsp;&nbsp;</span>Ausgewählte Methoden</a></span></li></ul></li></ul></li><li><span><a href="#Üben:-NumPy-and-Matplotlib" data-toc-modified-id="Üben:-NumPy-and-Matplotlib-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Üben: NumPy and Matplotlib</a></span></li></ul></div>

# NumPy

Tutorial: https://scipy-lectures.org/intro/numpy/index.html

- Der Datentyp `numpy.ndarray` und Vektorisierung
- Das Erzeugen von arrays
    - Ausgewählte Attribute
    - Funktionen zum Erzeugen
- Zugreifen auf Elemente des Arrays (slicing und indexing)
- Operationen mit und Manipulation von Arrays
    - Ausgewählte Methoden
    - Ausgewählte Funktionen
- (Broadcasting)

## Der Datentyp `numpy.ndarray` (the game changer!)
- verwaltet mehrdimensionale Arrays
- Array = geordnete Folge von gleichartigen Objekten, idR Zahlen
- mutable (wie `list`)
- sclicing/indexing über ganzzahlige Indices (wie bei `list` nur umfangreicher)

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
print(arr)
print(arr[0], arr[-1], arr[-2:-1])

Zwei Merkmale werden beim Erzeugen festgelegt:
- **Form (Attribut `.shape`)**: Dimensionen des Arrays
- **Datentyp (Attribut `.dtype`)**: Art der Daten die Elemente speichern können (kann nach Erzeugung nicht mehr verändert werden), z.B.:
    - `numpy.bool`
    - `numpy.int`
    - `numpy.float`
    - `numpy.complex`

In [ ]:
#print(arr, arr.shape, arr.dtype)
#arr = np.array([[1],[2],3,4]])
print(arr, arr.shape, arr.dtype)

#### Grundlegendes Konzept: Vektorisierung 

**Was ist das?**

"*Arrays are important because they enable you to express operations on data without writing any for loops. This is usually called vectorization.*"
 - ```python     
     arr = np.array([1,2,3,4])```
 - `arr` kann behandelt werden wie eine Zahl, zB `f(arr), arr+arr, 2*arr, arr+1`, wird dann elementweise ausgeführt
 - **Vorsicht (!!!):**
     - Matrix-Vektor-Produkt: `np.dot(A,x)` oder `A@x`
     - Matrix-Matrix-Produkt: `np.matmul(A,B)` oder `A@B`
 -  SciPy Stack ist hardwarenah implementiert (!)
     - mithilfe der mitgelieferten Funktionen können effiziente Programme geschrieben werden

In [ ]:
arr = np.array([1,2,3,4])
print(arr + arr)
print(arr * arr)
print(2 * arr)
print(arr + 1)
print(arr @ arr)

In [ ]:
def f(x):
    return x*x

# bisher 
y_list = []
for x in [-3, -2, -1, 0, 1, 2, 3]:
    y_list += [f(x)]   
print(y_list)

# jetzt
print(f(np.array([-3, -2, -1, 0, 1, 2, 3])))

**Demonstration**

Alle Array/Listen-Einträge Quadrieren

In [ ]:
L_list = range(5000000)
time = %timeit -o -q -r 1 [i**2 for i in L_list]
print("Zeit = ", time.best)


In [ ]:
import numpy as np
L_numpy = np.arange(5000000)
time = %timeit -o -q -r 1 L_numpy**2
print("Zeit = ", time.best)

**Weitere Begriffe in diesem Kontext:**
   - <a href ="https://de.wikipedia.org/wiki/Flynnsche_Klassifikation#SIMD_(Single_Instruction,_Multiple_Data)">**SIMD**</a> (Single Instruction, Multiple Data)
       - bezeichnet Rechner-Architektur
   -  <a href ="https://de.wikipedia.org/wiki/Vektorprozessor">**Vektorprozessor**</a> 
        - bestimmte Art von Prozessor (entwickelt für SIMD)

**Nicht zu verwechseln mit:**
 - einen Tensor zu einem Vektor transformieren (Mathematik)
 - Konvertierung von Rastergrafiken in Vektorgrafiken (Bildbearbeitung)

## Vektorisierte Funktion

= Funktion kann auf Arrays angewendet werden

 - Verknüpfung vektorisierter Funktionen idR wieder vektorisiert
 - (vektorisierte) Funktion von numpy und scipy hardwarenah = effizient
 - Ansonsten: function decorator `np.vectorize` (häufiges Problem: `if`- Anweisungen) 
     - Achtung: Geschwindigkeitsvorteil dieser Vektorisierung kommt nicht zwingend zum tragen

In [12]:
import numpy as np

@np.vectorize # = function decorator
def f(x): 
    if x > 0:
        return x**2  
    else:
        return 0
X = np.array([-3, -2, -1, 0, 1, 2, 3])
f(X)

array([0, 0, 0, 0, 1, 4, 9])

## Das Erzeugen von numpy.ndarrays


In [ ]:
arr = np.array([1,-2,3])
print(arr)
print(arr.dtype) # Attribut
print(arr.shape) # Attribut (gibt tuple zurück)
#
arr2 = np.array([ [1, 2 ],
                  [3, 4 ] ])
print(arr2)
print(arr2.dtype)
print(arr2.shape)

**Beobachtung:** Merkmal *Datentyp* wurde automatisch von numpy gewählt
 - numpy wählt den einfachsten Datentyp, um alle Werte zu speichern

Datentyp manuell wählen:

In [ ]:
arr = np.array([1,-2,3])
print(arr)
print(arr.dtype) # Attribut
print(arr.shape) # Attribut

In [ ]:
arr[0] = 1.9
print(arr)

Mehrdimensionale Arrays werden erzeugt durch verschachtelte Struktur

In [13]:
# Matrix 3x3
A = np.array([ [ 2., -1.,  0.],
               [-1.,  2., -1.],
               [ 0., -1.,  2.] ])
print(A, A.dtype, A.shape)

[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]] float64 (3, 3)


In [14]:
# Tensor  2 x 2 x 2
T = np.array([ [ [1., 0.],
                 [0., 1.]  ],
              #
               [ [2., 0.],
                 [0., 2.]  ]
             ])
print(T, T.dtype, T.shape)

[[[1. 0.]
  [0. 1.]]

 [[2. 0.]
  [0. 2.]]] float64 (2, 2, 2)


### Ausgewählte Attribute

- Attribut = ein Wert, der mit einem Objekt assoziert ist und per `object.attribute` abgefragt werden kann
- Begrifflichkeit aus der Objektorientierung von Python

- `.shape` $\checkmark$
- `.dtype` $\checkmark$
- `.ndim`
- `.size`

In [15]:
# Tensor  2x2x2
T = np.array([ [ [1., 0.],
                 [0., 1.]],
              #
               [ [2., 0.],
                 [0., 2.]]
             ])
print("T = \n", T, "\n")
print("Form                 =", T.shape)
print("numpy-Datentyp       =", T.dtype)
print("Anzahl Dimensionen   =", T.ndim)
print("Anzahl Elemente      =", T.size)

T = 
 [[[1. 0.]
  [0. 1.]]

 [[2. 0.]
  [0. 2.]]] 

Form                 = (2, 2, 2)
numpy-Datentyp       = float64
Anzahl Dimensionen   = 3
Anzahl Elemente      = 8


Bisher haben wir Arrays "manuell" erzeugt, nun:
### Funktionen zum Erzeugen von `numpy.ndarray`

Folgende Funktionen werden häufig in der Numerik gebraucht:
- `np.array(object)` 
- `np.ones(shape)`, `np.zeros(shape)`
- `np.linspace(start, stop, num)`
- `np.arange([start,] stop [,step])`
- `np.diag(...)`
- `np.eye(...)`
- `np.tile`, `np.repeat`
- `np.random.rand(d0, d1, ..., dn)`
- `np.empty(...)`
- (list comprehension)

##### Beispiele

In [ ]:
# np.array()
objct = [0,1,2]
arr = np.array(objct)
print(arr)

In [ ]:
# np.ones(shape)

shape = (5,) #  (5,5) 
np.ones(shape)  
# shape must be tuple
# np.ones(5,5)

In [ ]:
# np.zeros(shape)

shape = (5, 10) #  (5,5) 
np.zeros(shape)  
# shape must be tuple
#np.zeros(5,5)

1d Gitter

In [ ]:
# np.arange([start,] stop [,step])
import matplotlib.pyplot as plt
# Return evenly spaced values within a given interval.
# excluding `stop`
# For integer arguments the function is equivalent to the Python built-in `range` function,
# but returns an ndarray rather than a list.

start, stop, step = 1, 10, 1
rge = np.arange(start, stop, step)
print(rge*rge)
plt.plot(rge, np.zeros(len(rge)), 'ro')
plt.show()

In [ ]:
# np.linspace(start, stop, step)
num = 50
X = np.linspace(-10, 10, num, endpoint = True)
#print(grid)
#def f(x):
#    return x*x

plt.plot(X, 3 * np.sin(X)**3 + 2*X**2 + np.sin(X) + 6   , 'r-')

In [ ]:
# np.diag(array_like [, k])
# Extract a diagonal or construct a diagonal array.

k = -1
d = np.ones(5)
D = np.diag(d, k)
print(D)


In [ ]:
k2 = -1
d2 = np.diag(D, k2)
print(d2)

In [ ]:
# np.eye(N [, M, k])
# Return a 2-D array with ones on the diagonal and zeros elsewhere.

N, M, k = 40, 60, 10
A = np.eye(N, M, k, dtype = int)
B = np.eye(N,M, -k, dtype = int)
#print(A)
#print(B)
#print(A+B)
plt.figure()
plt.imshow(A)
plt.figure()
plt.imshow(B)
plt.figure()
plt.imshow(A+B)
plt.show()

Arrays vervielfachen

In [ ]:
# np.tile(arr, reps)
# Construct an array by repeating >arr< reps times .

arr = np.arange(5)
print(arr)
reps = 3
np.tile(arr, reps)

In [ ]:
arr = np.array([[1, 2],
                [3, 4]])
print(arr)
reps = (3,2) #(3,1) # (2,3)
np.tile(arr, reps)

Elemente innerhalb der arrays vervielfachen

In [ ]:
# np.repeat(arr, reps, axis=None)
# Repeat >elements< of an array.
arr = np.arange(5)
print(arr)
reps, axis = 3, 0 # 1
np.repeat(arr, reps, axis)


In [ ]:
# compare
np.tile(arr, reps)

In [ ]:
arr = np.array([[1, 2],
                [3, 4]])
print(arr)
reps, axis = 2, 1
np.repeat(arr, reps, axis)

Arrays mit Zufallszahlen

In [ ]:
# np.random.rand(d0, d1, ..., dn)
# Create an array of the given shape and populate it with random samples 
# from a uniform distribution over ``[0, 1)``.
d0, d1 = 3, 4
rndm1d = np.random.rand(d0)
rndm2d = np.random.rand(d0, d1)
print(rndm1d)
print()
print(rndm2d)

### Kombinationen

In [17]:
dim = 50
#A = np.zeros((dim,dim))
A = 2*np.eye(dim, dim, 0) - np.eye(dim, dim, 1) - np.eye(dim, dim, -1)
print(A)

[[ 2. -1.  0. ...  0.  0.  0.]
 [-1.  2. -1. ...  0.  0.  0.]
 [ 0. -1.  2. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  2. -1.  0.]
 [ 0.  0.  0. ... -1.  2. -1.]
 [ 0.  0.  0. ...  0. -1.  2.]]


In [ ]:
d = np.random.rand(dim)
D = np.diag(d)
print(D)

### Slicing (Zugriff auf Elemente im `numpy.ndarray`)

http://scipy-lectures.org/intro/numpy/array_object.html#indexing-and-slicing

- für 1d arrays wie bei Listen
    - Elemente, Teilarrays ersetzen
- für mehrdimensionale arrays für jede dimension wie 1d
    - Elemente, Teilarrays ersetzen

![](http://scipy-lectures.org/_images/numpy_indexing.png)

![](img/fancy_slicing_numpy.png)

In [ ]:
# Vektoren wie Listen
x = np.array(range(4))
print(x[2], x[2:], x[::-1])
x[2] = 8
print(x)

In [ ]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

## Zfs

- Der Datentyp: `numpy.ndarray` : verwaltet flexibel mehrdimensionale Arrays, mutable
- Vektorisierung: "*Arrays are important because they enable you to express operations on data without writing any for loops. This is usually called vectorization.*"
- Attribute: `.shape`, `.dtype`, `.ndim`, `.size`

**Funktionen zum Erzeugen von numpy arrays**
- `np.array(object)` 
- `np.ones(shape)`, `np.zeros(shape)`
- `np.linspace(start, stop, num)`
- `np.arange([start,] stop [,step])`
- `np.diag(...)`
- `np.eye(...)`
- `np.tile`, `np.repeat`
- `np.random.rand(d0, d1, ..., dn)`
- (`np.empty(...)`)
- (list comprehension)

Eine letzte sehr nützliche Funktion: `np.meshgrid`
- zur Erzeugung mehrdimensionaler regulärer Gitter
- Anwendung:
    - plotten von Funktionen $\mathbb{R}^2 \to \mathbb{R}$
    - Finite Elemente/ Finite Differenzen Diskretisierung auf Hyperrechtecken

In [ ]:
x = np.linspace(0,1.5,6)
y = np.linspace(0,0.5,6)
X, Y = np.meshgrid(x, y)
for i in range(len(X)):
    for j in range(len(X)):
        plt.plot(X[i][j], Y[i][j], 'o')
        plt.annotate(str(i)+str(j), xy=(x[i], y[j]), xytext=(x[i], y[j]), fontsize=16)
plt.axis('equal')
plt.show()

In [ ]:
# X mit repeat
print("X via repeat x")
print("x = ", x[np.newaxis, :])
print(X)
print(np.repeat(x[np.newaxis, :], 6, axis = 0))
# Y mit tile
print("Y via tile y")
print("y = ", y[np.newaxis, :])
print(Y) 
print(np.tile(y[:,np.newaxis], 6))

**INDEXING and SLICING**

![](http://scipy-lectures.org/_images/numpy_indexing.png)

## Operationen

- Elementweise
- Matrix-Vektor, Matrix-Matrix
- Transponieren
- Vergleichen
- Ausgewählte Methoden

### Elementweise Operationen

In [ ]:
x = np.arange(5)
y = np.ones(5)
print(x * y)
print(x + y)
print(x ** 2, x + 1)

In [ ]:
dim = 3
x = np.arange(dim)
A = np.eye(dim,dim,1)+np.eye(dim,dim,-1)-2*np.eye(dim,dim,0)
print(A)
print(x)
print(A*x)

### Matrix-Vektor Produkt `np.dot`, `@'

In [ ]:
A = np.eye(5,5,0)
x = np.arange(5)
print(A)#, "\n")
print(str(x)+ "\n")
print(A.dot(x), "\n")
print(np.dot(A,x), "\n")
#print(A@x, "\n")
#print(x@x, "\n")

### Matrix-Matrix Produkt `np.dot`, `@`, `np.matmul`

In [ ]:
A = np.eye(5,5,0)
B = np.ones((5,5))
print(A, "\n")
print(B, "\n")
print(A.dot(B), "\n")
print(np.matmul(A, B), "\n")
#print(A@B, "\n")

In [ ]:
A = np.eye(5,5,0)
x = np.ones(5)
print(A)
print(x)
print(A.dot(x))

### Transponieren `.T`, `.transpose()`

In [ ]:
A = 10 * np.eye(5,5,2, dtype = int) + 20 * np.eye(5,5,-2, dtype = int)
#print(A[:].T)
print(A.T)
print(A,"", [1,2])

### Vergleichen


In [ ]:
x = np.array([1  , 0,  1,  0])
z = np.array([1. , 0., 1., 0.0001])

In [ ]:
# component-wise
x == z

In [ ]:
# array-wise
#np.array_equal(x,z)
np.all(x == z), np.any(x == z)

In [ ]:
# array-wise up to tolerance
# True <=> |x-z| <= (atol + rtol *|z|)
np.allclose(x,z, rtol=1e-05, atol=1e-03), np.array_equal(x,z)

### Beachte: numpy arrays sind veränderlich!

In [ ]:
# Matrizen
x = np.eye(10, 10, 0, dtype = int)
x[6:10, 6:10] = 3 * np.ones((4,4), dtype = int)
x[0:2,  7:10] = -2
#print(x)
plt.imshow(x, vmin=-10, vmax=10)
plt.show()

In [ ]:
# Vorsicht bei mutable 
y = x[0:3, 0:3].copy()
y[0:3, 0:3] = -10
#print(x)
plt.imshow(x, vmin=-10, vmax=10)


### Ausgewählte Methoden

In [ ]:
dim = 4
A = np.zeros((dim,dim))
for i in range(dim):
    A += (np.eye(dim,dim,i) + np.eye(dim,dim,-i))*i

- Allgemein
    - `tolist()`
    - `copy()`

In [ ]:
# .tolist()
dim = 4
A = np.zeros((dim,dim))
for i in range(dim):
    A += (-np.eye(dim,dim,i) + np.eye(dim,dim,-i))*i**2
print(A)
print(A.tolist())
print(A)

In [ ]:
# .copy(), [:]
dim = 4
A = np.zeros((dim,dim))
for i in range(dim):
    A += np.eye(dim,dim,i)*i + np.eye(dim,dim,-i)*i**2
B = A.copy() # A[:]
np.fill_diagonal(A,666)
print(A)
print(B)

- Größenanpassung
    - `.reshape()`

In [ ]:
# .reshape()
num_el = A.size
print(A)
print(np.tile(A, 2).reshape(num_el,2))

- Berechnungen
    - `.max`, `.argmax`(und `.min`, `.argmin`)
    - `.sum` (und `.prod`)

In [ ]:
# .max(), .argmax()
x = np.arange(5)
x[3] = 10
print(x)
print(x.max())
print(x.argmax())
# analogously multi-dim arrays and min

In [ ]:
# .sum()
print(A)
print(A.sum())
print(A.sum(axis = 0)) # Spaltensumme
print(A.sum(axis = 1)) # Zeilensumme

Sortieren
 - `.sort()`

In [ ]:
dim = 4
A = np.zeros((dim,dim), dtype=int)
for i in range(dim):
    A += -np.eye(dim,dim,i, dtype=int)*i +np.eye(dim,dim,-i, dtype=int)*i**2
print("A =\n "+str(A)+ "\n")
B = A[:]
B.sort(axis = 0)
print("B2 =\n "+str(B)+"\n")
B = A[:]
B.sort(axis = 1)
print("B2 =\n "+str(B)+"\n")
B = A[:]
B.sort()
print("B3 =\n "+str(B)+"\n")

Nicht besprochen:
 - broadcasting Prinzip von numpy
 - flattening `.ravel`
 - `np.newaxis`:Indexing with the np.newaxis object allows us to add an axis to an array (you have seen this already above in the broadcasting section)

In [ ]:
x = np.array([0,1,2])
print(x[:, np.newaxis].shape)

Üben: NumPy and Matplotlib
====================


1.  Have a look at the first chapter of the scipy-lectures:
    https://scipy-lectures.org/ (namely, ’1. Getting started with Python
    for science’)

2.  Play around with the numpy functions: `arange`, `linspace`, `ones`,
    `zeros`, `eye`, `diag`, `tile`, `repeat` and `reshape`.

3.  Generate the following matrices:

    1.  Identity matrix

    2.  Zero matrix

    3.  A diagonal matrix
        $\left(D \in \mathbb{F}^{m\times n} ~\text{is called diagonal, if}~ d_{ij}=0 ~\forall i\neq j \right)$

    4.  Example matrix
        $$\left(\begin{array}{rrrr}                                
            1 &  1& 1 & 1\\                                               
            1 &  1& 1 & 1\\                                              
            1 &  1 &  1 & 2   \\ 
            1 &  6 &  1 & 1
            \end{array}\right) \nonumber$$

    5.  Example matrix
        $$\left(\begin{array}{rrrrr}                                
            0 &  0& 0 & 0&0\\                                               
            2 &  0& 0 & 0&0\\                                              
            0 &  3& 0 & 0&0\\ 
            0 &  0& 4 & 0&0\\ 
            0 &  0& 0 & 5&0\\ 
            0 &  0& 0 & 0&6
            \end{array}\right) \nonumber$$

    6.  Example matrix
        $$\left(\begin{array}{rrrrrr}                                
            4 &  3& 4 &3&4&3\\                                               
            2 &  1& 2 & 1&2&1\\                                              
            4 &  3& 4 & 3&4&3\\   
            2 &  1& 2 & 1&2&1
            \end{array}\right) \nonumber$$

    7.  Example matrix
        $$\left(\begin{array}{rrr}                                
            1  &6 &11\\                                               
            2  &7 &12\\                                              
            3  &8 &13\\   
            4  &9 &14\\
            5& 10 &15
            \end{array}\right) \nonumber$$

4.  Apply the functions `len()` and `numpy.shape()` to these arrays. How
    do the values relate? What does the attribute `ndim` tell us?

5.  Use `matplotlib.pyplot.imshow()` to visualize the matrices.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

""" 1. """ 

""" 2."""

m, n = 10, 5

# help(np.arange)
print(np.arange(1,n,2))
print(np.arange(n))

# help(np.linspace)
print(np.linspace(0,1,n, endpoint = False))

# help(np.ones)
print(np.ones(n))
print(np.ones((n,n)))

# help(np.zeros)
print(np.zeros(n))
print(np.zeros((n,n)))

# help(np.eye)
print(np.eye(n))
print(np.eye(m,n))
print(np.eye(m,n, 3))

# help(np.diag)
print(np.diag(np.ones(n)))
print(np.diag(np.ones(n), 3))


# help(np.tile)
print(np.tile(np.arange(3), 2))
print(np.tile(np.arange(3), (2, 3)))
print(np.tile(np.ones((2,2)), 3))

# help(np.repeat)
# Repeat elements of an array
print(np.repeat(np.arange(3), 2))
#print(np.repeat(np.arange(3), (2, 3)))
print(np.repeat(np.ones((2,2)), 3))
print(np.repeat(np.ones((2,2)), 3, axis = 1))

# help(np.reshape)
x = np.eye(3)
print(x)
print(np.reshape(x, 9))

""" 3."""
# a) identity matrix

# b) zero matrix

# c) diagonal matrix
d = np.arange(n)
A = np.diag(d)
print(np.diag(d))
print(len(A), np.shape(A), A.ndim)
plt.figure()
plt.imshow(A)
plt.show()

# d) 
A = np.ones((4,4))
A[3,1] = 6
A[2, 3] = 2
print(A)
print(len(A), np.shape(A), A.ndim)
plt.figure()
plt.imshow(A)
plt.show()

# e)
A = np.diag(np.arange(2,7,1), -1)
print(A)
print(len(A), np.shape(A), A.ndim)
plt.figure()
plt.imshow(A)
plt.show()

# f)
x = np.arange(4, 0,-1).reshape(2,2)
A = np.tile(x, (2, 3))
print(A)
print(len(A), np.shape(A), A.ndim)
plt.figure()
plt.imshow(A)
plt.show()

# g)
x = np.arange(1, 16)
A = np.reshape(x, (5,3), order = 'F')
print(A)
print(len(A), np.shape(A), A.ndim)
plt.figure()
plt.imshow(A)
plt.show()